// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCkiWhXrFimuMtr5MZ5_h13CS3LMU6w4Q',
    appId: '1:940891811096:android:b0fbadec81aa2119c7426d',
    messagingSenderId: '940891811096',
    projectId: 'hanpae-522da',
    storageBucket: 'hanpae-522da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcpdKkZkslCnKKXtaUWDcKaRmRdsirFGE',
    appId: '1:940891811096:ios:4ba3f979cbcf2594c7426d',
    messagingSenderId: '940891811096',
    projectId: 'hanpae-522da',
    storageBucket: 'hanpae-522da.appspot.com',
    iosClientId: '940891811096-5bas2dcn10h29arh71tu6qhq0j3lh39g.apps.googleusercontent.com',
    iosBundleId: 'com.example.hanpae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcpdKkZkslCnKKXtaUWDcKaRmRdsirFGE',
    appId: '1:940891811096:ios:4ba3f979cbcf2594c7426d',
    messagingSenderId: '940891811096',
    projectId: 'hanpae-522da',
    storageBucket: 'hanpae-522da.appspot.com',
    iosClientId: '940891811096-5bas2dcn10h29arh71tu6qhq0j3lh39g.apps.googleusercontent.com',
    iosBundleId: 'com.example.hanpae',
  );
}
